# Default configuration file which will be loaded automatically with framework
---
ENV_DATA:
  config_root: "~/config_root"

# Section for reporting configuration
REPORTING:
  email:
    address: "ocs-ci@redhat.com"
    smtp_server: "localhost"

# in this RUN section we will keep default parameters for run of noobaa-sa-ci
RUN:
  cli_params: {}
